### ISSUE TITLE
dont know how to use the programm

### ISSUE THREAD

**Issue by MrSneider** [AZn5ReD/saplearninghub-pdf-downloader#10]
Hi AZn5ReD,

im a big noob when it comes to coding. So i dont really understand how to use ur program.
I tried to write the command "npm install" in the Node.js. But it only says "npm should be run outside of the Node.js REPL, in your normal shell.(Press Ctrl+D to exit.)". 
Maybe you could help me with that whole installation and usage situation. Or maybe u have a link to a step by step guide for dummies.
Thank you very much

**Comment by sag8** [comment]
Use cmd instead of node js app.

Follow this.
https://stackoverflow.com/questions/24476805/how-to-resolve-npm-should-be-run-outside-of-the-node-repl-in-your-normal-shell

**Comment by MrSneider** [comment]
> 
> 
> Use cmd instead of node js app.
> 
> Follow this.
> https://stackoverflow.com/questions/24476805/how-to-resolve-npm-should-be-run-outside-of-the-node-repl-in-your-normal-shell

Thanks for the fast reply !
I had the installation path all wrong. With the right path it worked, but the the commands "run build" and "run start" gave me this wall of text:
npm run build npm run start

> saplearninghub-pdf-downloader@1.0.0 build C:\Users\soandso
> webpack -p "npm" "run" "start"

Hash: ea9ad599b672c4ad061e
Version: webpack 4.43.0
Time: 174ms
Built at: 03.12.2020 15:11:49
 1 asset
Entrypoint main = index.js
[0] multi npm run start 52 bytes {0} [built]

ERROR in multi npm run start
Module not found: Error: Can't resolve 'npm' in 'C:\Users\soandso'
 @ multi npm run start main[0]

ERROR in multi npm run start
Module not found: Error: Can't resolve 'run' in 'C:\Users\soandso'
 @ multi npm run start main[1]

ERROR in multi npm run start
Module not found: Error: Can't resolve 'start' in 'C:\Users\soandso'
 @ multi npm run start main[2]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! saplearninghub-pdf-downloader@1.0.0 build: `webpack -p "npm" "run" "start"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the saplearninghub-pdf-downloader@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\soandso\AppData\Roaming\npm-cache\_logs\2020-12-03T14_11_49_392Z-debug.log

do you know what might be the problem here?

Thanks anyway :) !

**Comment by AZn5ReD** [comment]
You can try the GUI version : https://github.com/AZn5ReD/saplearninghub-pdf-downloader-gui
