### ISSUE TITLE
rror while navToSF Error: Node is either not visible or not an HTMLElement

### ISSUE THREAD

**Issue by 94ajac** [AZn5ReD/saplearninghub-pdf-downloader#14]
Hi Dear @AZn5ReD ,

Thank you for all your patience and colaboration, I would like to send you a gift for this great tool, in fact is not still working for me, buy I know that is soimething easy to resolve, but I would like to say thank you in another way.

and also I want to share with my errors, I don't know what is going on, but maybe you can help me.

![image](https://user-images.githubusercontent.com/8475162/103471675-b08dd000-4d48-11eb-8c04-a694663d3a5f.png)

This is the error, and this is my configuration.

![image](https://user-images.githubusercontent.com/8475162/103471721-02365a80-4d49-11eb-8b4d-5260497fa0d4.png)

I set the timeout variable with X10 amout, but it did not work also.

Thanks in advance, it's maybe the same error of  @BobbyG83

This are some error that I'm able to read:

- Error while navToSF Error: Node is either not visible or not an HTMLElement

- waiting for selector "#progressIndicator" failed: timeout 30000ms exceeded

**Comment by AZn5ReD** [comment]
Hi,

Can you send me your mail or a way to contact you ? I can't reproduce the issue and I would like to try with your credentials.

**Comment by 94ajac** [comment]
> Hi,
> 
> Can you send me your mail or a way to contact you ? I can't reproduce the issue and I would like to try with your credentials.

**Comment by 94ajac** [comment]
Sure, aj_alvarez94@hotmail.com.
