### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ypcyc** [AZn5ReD/saplearninghub-pdf-downloader#17]
I'm stuck at "npm install"
As I understand there is some module dependency that tries to download "Minimal Qt 5.14.1",  and that link is not accessible 

That error was for saplearninghub-pdf-downloader-gui-masterversion I think

```
Minimal Qt 5.14.1 setup:
FetchError: request to https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt5_5141/qt.qt5.5141.win64_msvc2017_64/5.14.1-0-202001240957qtbase-Windows-Windows_10-MSVC2017-Windows-Windows_10-X86_64.7z failed, reason: connect ETIMEDOUT 77.86.229.90:443
```

**Comment by AZn5ReD** [comment]
You're on the wrong repo.
That said, unless you want to contribute to the project, you can directly download the [latest release](https://github.com/AZn5ReD/saplearninghub-pdf-downloader-gui/releases/tag/1.0.1) to use it.
