### ISSUE TITLE
Unable to follow the steps.. need help

### ISSUE THREAD

**Issue by viren2887** [AZn5ReD/saplearninghub-pdf-downloader#19]
Hi

I want to download the pdf from hub i try to follow the steps but not clear how to do it. As i have no experience in javasccript, so unable to run it. Can you please help me. 

Followed these steps
I have installed NodeJS in my window pc. 
I have chrome. 
In Config. json i have set the path and the user details.
Now whats the next step? How to execute it?

**Comment by AZn5ReD** [comment]
If you have no experience, you should probably use the GUI version ; https://github.com/AZn5ReD/saplearninghub-pdf-downloader-gui
