### ISSUE TITLE
Can't Connect / Error during init

### ISSUE THREAD

**Issue by bharatbjj** [AZn5ReD/saplearninghub-pdf-downloader#21]
Hi,

I tried to use your downloader but it's failing to connect. 
I'm using a windows machine and my SAP SUser ID is linked with the SAP Universal ID.

As per your instructions, I updated the `config.json` file with the chrome path, target directory, username, password. 
Also did the `npm install`, `npm build`, and `npm start`.

Then the script execution starts but after few steps, it throws the error: `Can't Connect / Error during init`.

Please see the attached screenshot:

![image](https://user-images.githubusercontent.com/503944/109913229-888b0080-7ce8-11eb-8707-7853e3145922.png)

Can you please suggest if I'm missing any step or doing something wrong?

Thanks in advance,
Bharat

**Comment by YassineKCD** [comment]
Same issue,
![image](https://user-images.githubusercontent.com/28400656/110019075-4f728080-7d28-11eb-91f3-78a45ee34a65.png)
Thanks in advance

**Comment by AZn5ReD** [comment]
@bharatbjj I don't get the same redirection after submitting : 
``` Redirected to: https://accounts.sap.com/saml2/idp/usso/Learning_Hub ```
Sorry, I can't help you because we don't have the same kind of access. I would need access to your user...

@Raskolnikovi I manage to get the same issue if I put the wrong credentials. Please check again your config file.

**Comment by Raskolnikovi** [comment]
@AZn5ReD I checked my credentials and i can login correctly using the same link in constants with my email and pass.

One thing tho, the constant URL_CONNECTED is not correct i dont land at https://saplearninghub.plateau.com/ but at https://performancemanager.successfactors.eu****

Which version of this repo are you using?

Thanks in advance

**Comment by Raskolnikovi** [comment]
@AZn5ReD I found the issue. It's not a problem of credentials. The first time you login with the script you have to accept a popup with terms and ... 
After that the script works just fine. But I think there is an issue the first time.
