### ISSUE TITLE
package.json not valid for bash

### ISSUE THREAD

**Issue by reallyallnamestaken** [AZn5ReD/saplearninghub-pdf-downloader#24]
In Bash one set environment variables using the "export" command "set" is used to set _internal_ Bash variables.
Since set is used in some other shells and Windows one should consider either making the script OS aware, or advise a different shell.
As a workaround one can set the variable manually prior to running npm e.g. "_export NODE_ENV=development"_

The answers here offer a couple options: https://stackoverflow.com/questions/45082648/npm-package-json-os-specific-script.

```
"scripts": {
    "build": "webpack -p",
    "start": "set NODE_ENV=production && node --no-deprecation ./dist/index.js ",
    "webpack-dev": "set NODE_ENV=development && webpack && node --no-deprecation ./dist/index.js",
    "dev": "set NODE_ENV=development && nodemon --exec babel-node --no-deprecation src/index.js"
  },
```

**Comment by AZn5ReD** [comment]
Yeah, nice catch. I had the issue and was working on installing cross-env and changing the script. I couldn’t make it work (or maybe I was too tired to understand). Anyway, I’ll try changing that soon. Also, if you have a better solution (or you’re faster than me), pull request are welcomed !
