### ISSUE TITLE
Universal ID

### ISSUE THREAD

**Issue by benebi** [AZn5ReD/saplearninghub-pdf-downloader#28]
Hello Azn5ReD,
My learning hub user is linked to SAP Universal ID and probably the password field is different in that case because here is my issue :

Entering password: ***
Error during login: a: waiting for selector "input[id='j_password']" failed: timeout 30000ms exceeded

Moreover, with the debug option, nothing is filled.

Can you please help ?
Thank you
Ben

**Comment by parthysing** [comment]
The problem with Universal ID is , two or more accounts are linked to one ID and on login it goes to the default account.
Get ur P or S ID from profile and use that ID to login

**Comment by adam0thman** [comment]
Even though you linked your S or P User IDs to your universal account, you can still log on using the individual S or P user IDs.. just get the actual S-User ID, you used for the SAP learning hub, but use the password of your Universal ID instead.

**Comment by benebi** [comment]
Thank you both, it works fine with S User and Universal ID passwd instead of S User password.
