### ISSUE TITLE
The downloaded Chinese ebook PDF can't show  the Chinese FONT

### ISSUE THREAD

**Issue by CoraLi1** [AZn5ReD/saplearninghub-pdf-downloader#29]
I want to download the Chinese version ebook, but the downloaded Chinese ebook PDF can't show  the Chinese FONT
the ebook link is below
`https://saplearninghub.plateau.com/icontent_e/CUSTOM_eu/sap/self-managed/ebook/S4F00_ZH_Col17/index.html`

- downloaded pdf ebook: 
<img width="657" alt="WX20210615-220912@2x" src="https://user-images.githubusercontent.com/20217076/122069320-af002200-ce27-11eb-944a-ade504eb56a3.png">

- online ebook:
<img width="733" alt="WX20210615-220740" src="https://user-images.githubusercontent.com/20217076/122069331-b0c9e580-ce27-11eb-80b0-0d94998c7453.png">

**Comment by CoraLi1** [comment]
[The problem has been solved](https://github.com/alafr/SVG-to-PDFKit/issues/35)

**Comment by wangjun127** [comment]
哈喽，你已经可以下载中文文档了吗，我还是不能下载，可以展示一下你的字体是怎么设置的吗 @CoraLi1

**Comment by CoraLi1** [comment]
你要先下载一个ttf文件

________________________________
发件人: wangjun127 ***@***.***>
发送时间: 2021年7月2日 10:25
收件人: AZn5ReD/saplearninghub-pdf-downloader ***@***.***>
抄送: CoraLi1 ***@***.***>; Mention ***@***.***>
主题: Re: [AZn5ReD/saplearninghub-pdf-downloader] The downloaded Chinese ebook PDF can't show the Chinese FONT (#29)


哈喽，你已经可以下载中文文档了吗，我还是不能下载，可以展示一下你的字体是怎么设置的吗 @CoraLi1<https://github.com/CoraLi1>

―

**Comment by CoraLi1** [comment]
> 哈喽，你已经可以下载中文文档了吗，我还是不能下载，可以展示一下你的字体是怎么设置的吗 @CoraLi1

已经解决了，可以看一下我的仓库

**Comment by iverson0709** [comment]
@

> > 哈喽，你已经可以下载中文文档了吗，我还是不能下载，可以展示一下你的字体是怎么设置的吗 @CoraLi1
> 
> 已经解决了，可以看一下我的仓库

可以指點怎麼使用嗎? 謝謝
